# Generated by Django 3.2.4 on 2021-07-06 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nomCompleto', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('contra', models.CharField(max_length=8)),
                ('img', models.ImageField(blank=True, null=True, upload_to='web/img')),
            ],
        ),
    ]
